version: '3.7'

services:
    psql:
        image: postgres:13.5-alpine
        expose:
        - 5432
        ports:
        - 5432:5432
        volumes:
        - "./data_db:/var/lib/postgresql/data"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        restart: always
    web:
        build: 
            context: .
            dockerfile: DockerfileNginx
        expose:
        - 8080
        ports:
        - "8080:8080"
        depends_on:
        - bingo
        - psql
    bingo:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
        - 4049:4049
        volumes:
        - "./opt:/opt/"
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 900M
                reservations:
                    cpus: '1'
                    memory: 900M
        depends_on:
            - psql
