student_email: alexeydad@yandex.ru
postgres_cluster:
  hosts:
  - address: 10.128.0.24
    port: 5432
  user: postgres
  password: postgres
  db_name: postgres
  ssl_mode: disable
  use_closest_node: false
